### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MironPingel** [plentymarkets/plentyshop-pwa#145]
### Expected Behavior

Loading the store.

### Actual Behavior

Store fails to load with:
`TypeError: Cannot read properties of null (reading 'items')`

### Possible Solution

In AppHeader.vue, changing:

```
    const wishlistTotalItems = computed(() => {
      const count = wishlist.value.items;

      return count ? count.length : null;
    });
```

to
```
    const wishlistTotalItems = computed(() => {
      const count = wishlist?.value?.items;

      return count ? count.length : null;
    });
```

### Steps to reproduce

Running a fresh clone of the current version of the repo.

### What version of plentymarkets integration are you using?

0.1.0

### What version of Node.js are you using?

v15.14.0

### What browser (and version) are you using?

Firefox

### What operating system (and version) are you using?

MacOS 13.2 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxiroellplenty** [comment]
Thanks 👍 This issue was solved in this pr: https://github.com/plentymarkets/plentyshop-pwa/pull/155
